# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pix', '0002_image_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=60),
        ),
    ]
